export const CHANGE_TOP_BANNER = "recommend/CHANGE_TOP_BANNER"
export const CHANGE_HOT_RECOMMEND = "recommend/CHANGE_HOT_RECOMMEND"
export const CHANGE_NEWALBUM = "recommend/CHANGE_NEWALBUM"

export const CHANGE_UP_RANKING = "recommend/CHANGE_UP_RANKING"
export const CHANGE_NEW_RANKING = "recommend/CHANGE_NEW_RANKING"
export const CHANGE_ORIGION_RANKING = "recommend/CHANGE_ORIGION_RANKING"

export const CHANGE_SETTLE_SINGER = "recommend/CHANGE_SETTLE_SINGER"